---
apiVersion: v1
kind: Secret
metadata:
  name: firefly-secret
  namespace: apps
type: Opaque
stringData:
  db-password: "ff_Ln6wQ3hV8jP5"
  app-key: "T/GHQgsXlM2HkCrkjr0dbgDnp7fbhkMp"
  cron-token: "15d02819f49742e88d58791ab37ea6a4"
