---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
  namespace: apps
  labels:
    app: toolbox
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - homeserver
      containers:
        - name: toolbox
          image: git.ramoneees.com/ramoneees/toolbox:v0.2.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: toolbox
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: toolbox
  ports:
    - name: http
      port: 8000
      targetPort: http
