apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - helmrelease.yaml
  - ingress.yaml
  - secrets.yaml
configMapGenerator:
  - name: authentik-helm-values
    files:
      - values.yaml=values.yaml
    options:
      disableNameSuffixHash: true
