---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: obsidian
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`notes.ramoneees.com`)
      kind: Rule
      services:
        - name: obsidian-vault
          port: 8080
  tls:
    secretName: wildcard-ramoneees-com-tls