# Flux Kustomization — Applications
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: namespaces
    - name: databases
  sourceRef:
    kind: GitRepository
    name: olympus
  path: ./apps
  prune: true
  timeout: 5m
