# Flux Kustomization — Infrastructure (Longhorn, CoreDNS, GPU Operator, Reloader)
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: olympus
  path: ./infrastructure
  prune: true
  timeout: 5m
