apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: librechat
  namespace: olympus
  labels:
    app: librechat
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ai.ramoneees.com`)
      kind: Rule
      services:
        - name: librechat
          port: 3080
  tls:
    secretName: wildcard-ramoneees-com-tls
