apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
  namespace: olympus
  labels:
    app: librechat
data:
  librechat.yaml: |
    version: 1.3.5
    cache: true
    endpoints:
      custom:
        - name: "OLYMPUS"
          apiKey: "${LITELLM_MASTER_KEY}"
          baseURL: "http://litellm.olympus.svc.cluster.local:4000/v1"
          models:
            fetch: true
          titleConvo: true
          titleModel: "MiniMax-M2.5"
          modelDisplayLabel: "OLYMPUS"
