apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-data
  namespace: olympus
  labels:
    app: librechat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
