---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: media-library-pv
  resources:
    requests:
      storage: 1500Gi
