# ArgoCD Applications — Shared Databases
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: "16.*"
      helm:
        valueFiles:
          - $values/databases/postgresql/values.yaml
    - repoURL: http://gitea-web.apps.svc.cluster.local:3000/ramoneees/olympus.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: mariadb
      targetRevision: "20.*"
      helm:
        valueFiles:
          - $values/databases/mariadb/values.yaml
    - repoURL: http://gitea-web.apps.svc.cluster.local:3000/ramoneees/olympus.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: "20.*"
      helm:
        valueFiles:
          - $values/databases/redis/values.yaml
    - repoURL: http://gitea-web.apps.svc.cluster.local:3000/ramoneees/olympus.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
