# Namespaces for the OLYMPUS cluster
# ArgoCD applies this first via a sync wave
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: olympus
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
