apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-home
  namespace: actions-runner
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
