apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenacitos-mission-control
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea-web.apps.svc.cluster.local:3000/ramoneees/olympus.git
    targetRevision: main
    path: apps/tenacitos
  destination:
    server: https://kubernetes.default.svc
    namespace: olympus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false  # olympus namespace already exists