apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenacitos-mission-control
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ramoneees/olympus
    targetRevision: HEAD
    path: apps/tenacitos
  destination:
    server: https://kubernetes.default.svc
    namespace: tenacitos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true