---
apiVersion: v1
kind: Secret
metadata:
  name: invoice-ninja-secret
  namespace: apps
type: Opaque
stringData:
  db-password: "inv_Cd9tY5mN7kF2"
  app-key: "base64:YilBpYrLyg1p1R+MeHwWodF5QNoKdm0GQmCAfXNcYAg="
