# Mattermost Team Edition
# Chart: mattermost-team-edition
# Repo: https://helm.mattermost.com

image:
  repository: mattermost/mattermost-team-edition
  tag: latest

persistence:
  data:
    enabled: true
    storageClass: longhorn
    size: 5Gi
  plugins:
    enabled: true
    storageClass: longhorn
    size: 1Gi

mysql:
  enabled: false

externalDB:
  enabled: true
  externalDriverType: postgres
  externalConnectionString: "mattermost:mm_Rj3wN8yT5kB6@postgresql.databases.svc.cluster.local:5432/mattermost?sslmode=disable"

config:
  MM_SERVICESETTINGS_SITEURL: "https://chat.ramoneees.com"
  MM_SQLSETTINGS_DRIVERNAME: "postgres"
  MM_SQLSETTINGS_DATASOURCE: "postgres://mattermost:mm_Rj3wN8yT5kB6@postgresql.databases.svc.cluster.local:5432/mattermost?sslmode=disable"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
