# Mattermost Team Edition
# Chart: mattermost-team-edition
# Repo: https://helm.mattermost.com

image:
  repository: mattermost/mattermost-team-edition
  tag: latest

persistence:
  data:
    enabled: true
    storageClass: longhorn
    size: 5Gi
  plugins:
    enabled: true
    storageClass: longhorn
    size: 1Gi

mysql:
  enabled: false

externalDB:
  enabled: true
  externalDriverType: postgres
  externalConnectionString: "mattermost:mm_Rj3wN8yT5kB6@postgresql.databases.svc.cluster.local:5432/mattermost?sslmode=disable"

config:
  MM_SERVICESETTINGS_SITEURL: "https://chat.ramoneees.com"
  MM_SERVICESETTINGS_ALLOWUNTRUSTEDINTERNALCONNECTIONS: "true"
  MM_TEAMSETTINGS_ENABLEOPENSERVER: "true"
  MM_TEAMSETTINGS_ENABLETEAMCREATION: "true"
  MM_TEAMSETTINGS_EXPERIMENTALPRIMARYTEAM: "olympus"
  MM_SQLSETTINGS_DRIVERNAME: "postgres"
  MM_SQLSETTINGS_DATASOURCE: "postgres://mattermost:mm_Rj3wN8yT5kB6@postgresql.databases.svc.cluster.local:5432/mattermost?sslmode=disable"

securityContext:
  fsGroup: 2000
  runAsUser: 2000
  runAsGroup: 2000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  externalPort: 8065
  internalPort: 8065
  annotations: {}
  loadBalancerSourceRanges: []

extraDeploy:
  - apiVersion: v1
    kind: Service
    metadata:
      name: mattermost-nodeport
      labels:
        app.kubernetes.io/name: '{{ include "mattermost-team-edition.name" . }}'
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
        helm.sh/chart: '{{ include "mattermost-team-edition.chart" . }}'
    spec:
      type: NodePort
      selector:
        app.kubernetes.io/name: '{{ include "mattermost-team-edition.name" . }}'
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
      ports:
        - port: 8065
          targetPort: http
          protocol: TCP
          name: mattermost
