apiVersion: v1
kind: ConfigMap
metadata:
  name: mundados-config
  namespace: apps
data:
  S3_ENDPOINT: "http://minio.apps.svc.cluster.local:9000"
  LITELLM_URL: "http://litellm.apps.svc.cluster.local:4000"
  S3_BUCKETS_RAW: "mundados-raw"
  S3_BUCKETS_BRONZE: "mundados-bronze"
  POSTGRES_HOST: "postgres-svc.apps.svc.cluster.local"
  POSTGRES_DB: "mundata"
  POSTGRES_USER: "mundata"
  LITELLM_CHAT_MODEL: "qwen3.5:9b"
  CHAT_RATE_LIMIT: "10"
