apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - helmrelease.yaml
  - secrets.yaml
  - pgvector-reindex-job.yaml
configMapGenerator:
  - name: postgresql-helm-values
    files:
      - values.yaml=values.yaml
    options:
      disableNameSuffixHash: true
