apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard/
  - authentik/
  - cloudbeaver/
  - firefly-iii/
  - gitea/
  - gitea-runner/
  - home-assistant/
  - homebox/
  - invoice-ninja/
  # - mattermost/  # suspended 2026-04-23
  - obsidian/
  - uptime-kuma/
  - vaultwarden/
  # - vikunja/  # suspended 2026-04-23
  - weserve/
  - weserve-tunnel/
  - searxng/
  - zotero/
