apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard/
  - ai-git-bot/
  - cloudbeaver/
  - firefly-iii/
  - gitea/
  - gitea-runner/
  - home-assistant/
  - homebox/
  - invoice-ninja/
  - ghost/
  - obsidian/
  - pack-website/
  - paperclip/
  - toolbox/
  - weserve/
  - weserve-tunnel/
  - cloudbeaver-tunnel/
  - zotero/
