apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard/
  - ai-gitea-bot/
  - cloudbeaver/
  - firefly-iii/
  - gitea/
  - gitea-runner/
  - home-assistant/
  - homebox/
  - invoice-ninja/
  - me-portfolio/
  - obsidian/
  - toolbox/
  - weserve/
  - weserve-tunnel/
  - zotero/
