---
apiVersion: v1
kind: Secret
metadata:
  name: mission-control-secret
  namespace: olympus
type: Opaque
stringData:
  admin-password: "Olympus2026!"
  auth-secret: "Goey0No+NZs01csqZIJGwDCWSassheaKdjQ6IgqtCN8="
  gateway-token: "7ddd85d8f40c4e62172a8b00445c269eafceec4b335db233"
  api-key: "d9f4ae468e071a88e6851351851d309c7220e4d159295b23"
