---
apiVersion: v1
kind: Secret
metadata:
  name: mission-control-secret
  namespace: olympus
type: Opaque
stringData:
  admin-password: "Olympus2026!"
  auth-secret: "Goey0No+NZs01csqZIJGwDCWSassheaKdjQ6IgqtCN8="
  gateway-token: "b356c72fae24b1abd0a781bd399ca8624f384b20df05345e"
  api-key: "d9f4ae468e071a88e6851351851d309c7220e4d159295b23"
