# Traefik IngressRoute for Gitea
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`git.ramoneees.com`)
      kind: Rule
      services:
        - name: gitea-web
          port: 3000
  tls:
    secretName: wildcard-ramoneees-com-tls
